name: Train and save model to GCS

on:
  workflow_dispatch:  # allows manual triggering

defaults:
  run:
    working-directory: LAB3-GithubLabs  # all commands run inside this folder

jobs:
  train_and_save:
    runs-on: ubuntu-latest

    steps:
      # Step 0: Checkout repo
      - name: Checkout the code
        uses: actions/checkout@v4

      # Step 1: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 2: Cache pip dependencies
      - name: Get cache dir 
        id: pip-cache-dir
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Step 4: Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Step 5: Train the model
      - name: Train model
        id: train
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}  # added
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}  # added
        run: python train_and_save_model.py

      # Step 6: Upload confirmation message (runs only if accuracy ≥ 75%)
      - name: Upload to GCS and send report
        if: success()
        run: echo "Model met accuracy threshold, uploaded to GCS and report emailed."
